"""corigindo variaveis da tabela filtros

Revision ID: 056ec4f18a2f
Revises: e1133f0bdbd0
Create Date: 2025-02-10 20:46:10.214128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '056ec4f18a2f'
down_revision = 'e1133f0bdbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evitar_pedagios', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('evitar_estradas_nao_pavimentadas', sa.Boolean(), nullable=False))
        batch_op.drop_column('evitar_estradas_não_pavimentadas')
        batch_op.drop_column('evitar_pedágios')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evitar_pedágios', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('evitar_estradas_não_pavimentadas', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('evitar_estradas_nao_pavimentadas')
        batch_op.drop_column('evitar_pedagios')

    # ### end Alembic commands ###
