"""Adicionado a tabela Filtros e relacionamententre Filtros e Pesquisa

Revision ID: 0e2423e895ef
Revises: 68ec66cba773
Create Date: 2025-02-06 18:35:12.355195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2423e895ef'
down_revision = '68ec66cba773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filtros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pesquisa_id', sa.Integer(), nullable=False),
    sa.Column('modo_transporte', sa.Enum('carro', 'moto', 'bicicleta', 'ônibus', 'a pé'), nullable=False),
    sa.Column('evitar_rodovias', sa.Boolean(), nullable=False),
    sa.Column('evitar_transito_pesado', sa.Boolean(), nullable=False),
    sa.Column('evitar_pedágios', sa.Boolean(), nullable=False),
    sa.Column('evitar_estradas_não_pavimentadas', sa.Boolean(), nullable=False),
    sa.Column('rota_mais_curta', sa.Boolean(), nullable=False),
    sa.Column('rota_mais_longa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['pesquisa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pesquisa', schema=None) as batch_op:
        batch_op.drop_index('destino')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pesquisa', schema=None) as batch_op:
        batch_op.create_index('destino', ['destino'], unique=True)

    op.drop_table('filtros')
    # ### end Alembic commands ###
