"""Criando a tabela pesquisa

Revision ID: 68ec66cba773
Revises: 
Create Date: 2025-02-05 19:33:32.252411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ec66cba773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origem', sa.String(length=300), nullable=False),
    sa.Column('destino', sa.String(length=300), nullable=False),
    sa.Column('data_e_hora', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destino')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesquisa')
    # ### end Alembic commands ###
