"""Adicionando a tabela HistoricoPesquisa

Revision ID: d47ea69174ef
Revises: 0e2423e895ef
Create Date: 2025-02-06 18:56:35.807652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47ea69174ef'
down_revision = '0e2423e895ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pesquisa_id', sa.Integer(), nullable=False),
    sa.Column('data_pesquisa', sa.DateTime(), nullable=False),
    sa.Column('vezes_pesquisada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['pesquisa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_pesquisa')
    # ### end Alembic commands ###
