"""Adicioando a tabela ResultadoPesquisa

Revision ID: e1133f0bdbd0
Revises: d47ea69174ef
Create Date: 2025-02-06 19:52:16.828077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1133f0bdbd0'
down_revision = 'd47ea69174ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultado_pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pesquisa_id', sa.Integer(), nullable=False),
    sa.Column('rota', sa.String(300), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['pesquisa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_pesquisa')
    # ### end Alembic commands ###
